name: docker

on:
    pull_request:
        branches: [main]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install bazelisk
              run: |
                  curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
                  mkdir -p "${GITHUB_WORKSPACE}/bin/"
                  mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
                  chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      ${{github.repository}}
                  tags: |
                      type=semver,pattern={{major}}.{{minor}}.{{patch}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=ref,event=pr

            - name: Build base image with Bazel
              run: |
                  bazel build //src:image.tar 
                  docker load -i bazel-bin/src/image.tar

            - name: Push
              run: |
                  env
                  echo $DOCKER_METADATA_OUTPUT_TAGS
                  for tag in $(jq -r '.tags[]' <<< "$DOCKER_METADATA_OUTPUT_JSON"); do
                    echo $tag
                    docker tag bazel/src:image $tag
                  done
